#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Stop services
        systemctl stop cct-pocketbase.service || true
        systemctl stop cct-daemon.service || true

        # Disable services
        systemctl disable cct-pocketbase.service || true
        systemctl disable cct-daemon.service || true
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
